apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-demo
  template:
    metadata:
      labels:
        app: platform-demo
    spec:
      containers:
        - name: platform-demo
          image: 10mey/platform-demo:04f9106511a8ac599060262adbc2606412a7eb03
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: LOG_LEVEL
              value: "DEBUG"
